version: '3.8'
services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
  database:
    image: mongo:3.6.18-xenial
    expose:
      - 27017
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
